# Import Liberaries 

In [157]:
import json 
import re 
from sklearn.preprocessing import LabelEncoder
import numpy as np 
import tensorflow as tf
from tensorflow.keras.utils import to_categorical
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences

Read Data

In [158]:
with open('data.json') as file:
    data=json.load(file)

In [159]:
data

{'data': [{'label': 'greeting',
   'patterns': ['Hi', 'Hey', 'Is anyone there?', 'Hello', 'Hay'],
   'responses': ['Hello', 'Hi', 'Hi there', 'Hey']},
  {'label': 'about',
   'patterns': ['Who are you?', 'What are you?', 'Who you are?'],
   'responses': ["I'm Zain, your bot assistant",
    "I'm Zain , an Artificial Intelligent bot",
    "I'm Zain , an Amit Artificial Intelligent bot"]},
  {'label': 'name',
   'patterns': ['what is your name?',
    'what should I call you?',
    'whats your name?'],
   'responses': ['You can call me Zain.',
    "I'm Zain!",
    'Just call me as Zain']},
  {'label': 'help',
   'patterns': ['Could you help me?',
    'give me a hand please.',
    'Can you help?',
    'What can you do for me?',
    'I need a support.',
    'I need a help',
    'support me please'],
   'responses': ['Tell me how can assist you',
    'Tell me your problem to assist you',
    'Yes Sure, How can I support you']},
  {'label': 'sad',
   'patterns': ["I'm sad",
    "I'm so sad",
 

Create training example , label and response 

In [160]:
training_example=[]
training_labels=[]
response=[]

for example in data['data']:
    for pattern in example['patterns']:
        training_example.append(pattern)
        training_labels.append(example['label'])
    response.append(example['responses'])


In [161]:
print("training example ")
print(training_example)

training example 
['Hi', 'Hey', 'Is anyone there?', 'Hello', 'Hay', 'Who are you?', 'What are you?', 'Who you are?', 'what is your name?', 'what should I call you?', 'whats your name?', 'Could you help me?', 'give me a hand please.', 'Can you help?', 'What can you do for me?', 'I need a support.', 'I need a help', 'support me please', "I'm sad", "I'm so sad", 'I feel bad', 'I am alone', 'I have a lot of problems', 'I am depressed', 'I need encouragement', "I'm so frustrated", "I'm so frustrated with myself because I lost confidence", 'Thanks', 'Thank you', "That's helpful", 'Thanks for the help', 'Bye', 'See you later', 'Goodbye']


In [162]:
print("training label ")
print(training_labels)

training label 
['greeting', 'greeting', 'greeting', 'greeting', 'greeting', 'about', 'about', 'about', 'name', 'name', 'name', 'help', 'help', 'help', 'help', 'help', 'help', 'help', 'sad', 'sad', 'sad', 'sad', 'sad', 'positive_sen', 'positive_sen', 'positive_sen', 'positive_sen', 'thanks', 'thanks', 'thanks', 'thanks', 'goodbye', 'goodbye', 'goodbye']


In [163]:
print('Response')
print(response)

Response
[['Hello', 'Hi', 'Hi there', 'Hey'], ["I'm Zain, your bot assistant", "I'm Zain , an Artificial Intelligent bot", "I'm Zain , an Amit Artificial Intelligent bot"], ['You can call me Zain.', "I'm Zain!", 'Just call me as Zain'], ['Tell me how can assist you', 'Tell me your problem to assist you', 'Yes Sure, How can I support you'], ['It is better for you to pray', 'Get close to Allah', 'You can watch a movie', 'Go out with friends'], ['I think you are great!', 'You are a genius!', 'You are awesome'], ['Happy to help!', 'Any time!', 'My pleasure', "You're most welcome!"], ['See you later', 'Have a nice day', 'Bye! Come back again']]


In [164]:
len(training_labels)

34

In [165]:
len(set(training_labels))

8

Preprocessing

In [166]:
training_example

['Hi',
 'Hey',
 'Is anyone there?',
 'Hello',
 'Hay',
 'Who are you?',
 'What are you?',
 'Who you are?',
 'what is your name?',
 'what should I call you?',
 'whats your name?',
 'Could you help me?',
 'give me a hand please.',
 'Can you help?',
 'What can you do for me?',
 'I need a support.',
 'I need a help',
 'support me please',
 "I'm sad",
 "I'm so sad",
 'I feel bad',
 'I am alone',
 'I have a lot of problems',
 'I am depressed',
 'I need encouragement',
 "I'm so frustrated",
 "I'm so frustrated with myself because I lost confidence",
 'Thanks',
 'Thank you',
 "That's helpful",
 'Thanks for the help',
 'Bye',
 'See you later',
 'Goodbye']

In [167]:
def clean_text(sentences):
    result=[]
    for sentence in sentences:
        #sentence=re.sub(r'\W',' ',sentence)# pattern  # text 
        sentence=sentence.lower()
        result.append(sentence)
        
    return result

In [168]:
training_example=clean_text(training_example)

In [169]:
training_example

['hi',
 'hey',
 'is anyone there?',
 'hello',
 'hay',
 'who are you?',
 'what are you?',
 'who you are?',
 'what is your name?',
 'what should i call you?',
 'whats your name?',
 'could you help me?',
 'give me a hand please.',
 'can you help?',
 'what can you do for me?',
 'i need a support.',
 'i need a help',
 'support me please',
 "i'm sad",
 "i'm so sad",
 'i feel bad',
 'i am alone',
 'i have a lot of problems',
 'i am depressed',
 'i need encouragement',
 "i'm so frustrated",
 "i'm so frustrated with myself because i lost confidence",
 'thanks',
 'thank you',
 "that's helpful",
 'thanks for the help',
 'bye',
 'see you later',
 'goodbye']

convert label values

In [170]:
le=LabelEncoder()
le.fit(training_labels)
training_labels=le.fit_transform(training_labels)

In [171]:
training_labels

array([2, 2, 2, 2, 2, 0, 0, 0, 4, 4, 4, 3, 3, 3, 3, 3, 3, 3, 6, 6, 6, 6,
       6, 5, 5, 5, 5, 7, 7, 7, 7, 1, 1, 1], dtype=int64)

In [172]:
# Initialize the LabelEncoder
le = LabelEncoder()

# Fit and transform the training labels
training_labels_encoded = le.fit_transform(training_labels)

# Convert the encoded labels into categorical format
training_labels_categorical = to_categorical(training_labels_encoded)

Convert words to vectors

In [173]:
from tensorflow.keras.preprocessing.text import one_hot 
sequnces=[one_hot(example,50,filters='') for example in training_example]
print(sequnces)

[[33], [42], [4, 39, 24], [42], [6], [37, 5, 33], [35, 5, 33], [37, 42, 46], [35, 4, 35, 37], [35, 16, 25, 3, 33], [28, 35, 37], [18, 42, 34, 47], [41, 32, 46, 28, 11], [44, 42, 16], [35, 44, 42, 39, 9, 47], [25, 35, 46, 13], [25, 35, 46, 34], [31, 32, 29], [34, 23], [34, 31, 23], [25, 11, 16], [25, 8, 35], [25, 15, 46, 11, 23, 31], [25, 8, 24], [25, 35, 12], [34, 31, 44], [34, 31, 44, 1, 49, 20, 25, 22, 38], [26], [35, 42], [22, 23], [26, 9, 39, 34], [22], [39, 42, 15], [7]]


In [174]:
toknizer=Tokenizer(num_words=100)
toknizer.fit_on_texts(training_example)
sequnces=toknizer.texts_to_sequences(training_example)
print(sequnces)

[[23], [24], [11, 25, 26], [27], [28], [12, 8, 1], [3, 8, 1], [12, 1, 8], [3, 11, 13, 14], [3, 29, 2, 30, 1], [31, 13, 14], [32, 1, 4, 5], [33, 5, 6, 34, 15], [16, 1, 4], [3, 16, 1, 35, 17, 5], [2, 9, 6, 18], [2, 9, 6, 4], [18, 5, 15], [7, 19], [7, 10, 19], [2, 36, 37], [2, 20, 38], [2, 39, 6, 40, 41, 42], [2, 20, 43], [2, 9, 44], [7, 10, 21], [7, 10, 21, 45, 46, 47, 2, 48, 49], [22], [50, 1], [51, 52], [22, 17, 53, 4], [54], [55, 1, 56], [57]]


In [175]:
padded_sequence=pad_sequences(sequnces,truncating='post',maxlen=20)
print(padded_sequence)

[[ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0 23]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0 24]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0 11 25 26]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0 27]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0 28]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0 12  8  1]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  3  8  1]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0 12  1  8]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  3 11 13 14]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  3 29  2 30  1]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0 31 13 14]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0 32  1  4  5]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0 33  5  6 34 15]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0 16  1  4]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  3 16  1 35 17  5]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  2  9

In [176]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense ,LSTM,Embedding ,GlobalAveragePooling1D

model=Sequential()
model.add(Embedding(100,10))
model.add(GlobalAveragePooling1D())
model.add(Dense(10,activation='relu'))
model.add(Dense(10,activation='relu'))
model.add(Dense(8,activation='softmax'))


model.compile(loss='categorical_crossentropy',optimizer='adam',metrics=['accuracy'])
model.summary()

Model: "sequential_27"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_27 (Embedding)        │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ global_average_pooling1d_13     │ ?                      │   0 (unbuilt) │
│ (GlobalAveragePooling1D)        │                        │               │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_33 (Dense)                │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_34 (Dense)                │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_35 (Dense)                │ ?                      │   0 (unbuilt) │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [177]:
history=model.fit(np.array(padded_sequence),training_labels,epochs=400)


Epoch 1/400


ValueError: Arguments `target` and `output` must have the same rank (ndim). Received: target.shape=(None,), output.shape=(None, 8)

Save Model

In [ ]:
inp='hello'
sent=pad_sequences(toknizer.texts_to_sequences([inp]),maxlen=20)
print(sent)
result=np.argmax(model.predict(np.array(sent))) # 0-7 
print(result)
f_res=le.inverse_transform(np.array(result).reshape(1))
print(f_res)

## Save Model


In [ ]:
import pickle as pk 
#save tokinizer
pk.dump(toknizer,open("toknizer.pkl","wb"))

In [ ]:
#save encoder
pk.dump(le,open("label_encoder.pkl","wb"))

In [ ]:
model.save('model.h5') # save model 
from tensorflow.keras.models import load_model
model=load_model('model.h5') # load model 

Interface

In [ ]:
def user_chat():
    while True :
        print("User : ",end="") 
        inp=input()

        if inp.lower()=='quit':
            break
        
        sent=pad_sequences(toknizer.texts_to_sequences([inp]),maxlen=20) #[] len=20

        result=np.argmax(model.predict(np.array(sent),verbose=0)) # 0-7 
        # 2 ,3 , 4
        f_res=le.inverse_transform(np.array(result).reshape(1))


        for label in data['data']:

            if label['label']==f_res:

                print('ChatBot : ',np.random.choice(label['responses']))



In [ ]:
print("Start Conversation with Chatbot")
user_chat()